# Generated by Django 5.2 on 2025-05-11 17:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('location', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('tel', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('working_hours', models.CharField(blank=True, default='8 - 16', max_length=50, null=True)),
                ('type', models.CharField(choices=[('business', 'Business'), ('customer', 'Customer')], default='customer', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
